[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x7ca418501293bb78edc0d35b147ae179f9526e61f23aa71faf8964b64e7b7914'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]